### ISSUE TITLE
ModuleNotFoundError: No module named 'ProbLabelPropagation'

### ISSUE THREAD

**Issue by YimingCuiCuiCui** [alex-xun-xu/WeakSupPointCloudSeg#1]
Thank you for sharing your code!

However, I got an error when I tried to use your code. I think there should be some parts of the codes missing. Could you try to help me figure that out? Thank you!

**Comment by alex-xun-xu** [comment]
Hi Yiming. I am still updating the project. The new version should work for ShapeNet. I will update the S3DIS dataset very soon.

**Comment by YimingCuiCuiCui** [comment]
Hi Xun, thank you very much!

**Comment by Violetit** [comment]
Hi @alex-xun-xu 
The same error about
`ModuleNotFoundError: No module named 'ProbLabelPropagation'`

Could you help us solve this problem?
Waiting for your reply!

**Comment by alex-xun-xu** [comment]
> Hi @alex-xun-xu
> The same error about
> `ModuleNotFoundError: No module named 'ProbLabelPropagation'`
> 
> Could you help us solve this problem?
> Waiting for your reply!

I forgot to upload the ProbLabelPropagation file. It should be fixed now.

**Comment by miaodzz** [comment]
> > Hi @alex-xun-xu
> > The same error about
> > `ModuleNotFoundError: No module named 'ProbLabelPropagation'`
> > Could you help us solve this problem?
> > Waiting for your reply!
> 
> I forgot to upload the ProbLabelPropagation file. It should be fixed now.

Hello, I searched the entire folder but still can't find any files about 'SmoothConstraint' and 'ProbLabelPropagation' .
Could you upload them again? Thank you very much.
